# source("renv/activate.R")
cat("Welcome to the treesinspace project.\n")
devtools::load_all("~/treesinspace")
devtools::load_all("~/slendr_treesinspace") # this is the correct version of slendr for compatibility. Pulled from https://github.com/bodkan/slendr.git
require(ggplot2)
require(tidyverse)
require(ape)
require(sf)
require(MetBrewer)
require(ggrepel)
require(ggpubr)
require(ggtree)
require(moments)
require(phangorn)
require(apTreeshape)
require(VGAM)
require(scales)
require(beeswarm)
require(ggbeeswarm)
require(ohenery)
require(kableExtra)
require(testthat)
require(cowplot)
# setting up slendr virtual environment
setup_env()
check_env()

