cat("Welcome to the treesinspace project.\n")
require(slendr)
devtools::load_all("~/treesinspace")
require(ggplot2)
require(tidyverse)
require(ape)
require(sf)
require(MetBrewer)
require(ggrepel)
require(ggpubr)
require(ggtree)
require(moments)
require(phangorn)
require(apTreeshape)
require(VGAM)
require(scales)
require(beeswarm)
require(ggbeeswarm)
require(ohenery)
require(kableExtra)
require(testthat)
require(cowplot)
# setting up slendr virtual environment
setup_env()
init_env()
check_env()

