---
title: "R Notebook"
output: html_notebook
---

Wide trees

```{r}
devtools::load_all()
library(tidyverse)
library(ape)
library(sf)
library(MetBrewer)
library(ggrepel)
library(ggpubr)
library(ggtree)
library(moments)
library(phangorn)
library(apTreeshape)
devtools::load_all("~/slendr")
setup_env()
check_env()
```

```{r}
# defining parameters
n <- 200
Ns <- n
mat_dists <- c(20,50,Ns * 4) # mate distance
comp_dists <- c(0,10,50,Ns * 4) # competition distance
disp_dists <- 1 # mean dispersal distance
disp_funs <- c("brownian","normal","cauchy","uniform")
reps <- c(1:3)
ngens <- Ns * 4 # expected time to coalescence

# let's also make a parameter table
pars <- expand.grid(N=Ns,
                    mat_dist=mat_dists,
                    comp_dist=comp_dists,
                    disp_fun=disp_funs,
                    disp_dist=disp_dists,
                    rep=reps,
                    ngen=ngens)
```

Now, I run a series of simulations with these parameters. 

```{r, warning=FALSE}
# defining a region
map <- world(
  # let's make this very large so that we avoid edge effects
  xrange = c(-ngens*4, ngens*4), # min-max longitude
  yrange = c(-ngens*4, ngens*4), # min-max latitude
  landscape = "blank"
)

# running the model
trees <- c()
trees_us <- c()
conns <- c()
i <- 1

for (row in c(1:dim(pars)[1])){

  # define a population
  pop <- population("POP",
                    time = 1,
                    N = pars[row,"N"],
                    center = c(0,0),
                    radius = ngens,
                    map = map,
                    mate_dist = pars[row,"mat_dist"],
                    competition_dist = pars[row,"comp_dist"],
                    dispersal_fun = as.character(pars[row,"disp_fun"]),
                    dispersal_dist = pars[row,"disp_dist"])

  # compile and run the model
  model <- compile(
    populations = pop,
    generation_time = 1,
    sim_length = ngens, # a forward in time model in slendr needs length of the sim
    resolution = 1, # resolution in "distance units per pixel"
    # how can we control this distribution?
    path = "~/Desktop/test-model",
    overwrite = TRUE
  )

  # let's sample 10 individuals in the "present"
  samples <- sampling(model, times = ngens, list(pop, n/2))

  # simulate
  slim(
    model, sampling = samples,
    sequence_length = 1,
    recombination_rate = 0, # simulate only a single locus
    method = "batch", # change to "gui" to execute the model in SLiMgui
    random_seed = 5*i,
    verbose = FALSE,
    retainall = TRUE,
    burnin = 0,
  )

  # extract trees
  ts <- ts_load(model, simplify = TRUE) %>%
    ts_recapitate(Ne = pars[row,"N"],
                  recombination_rate = 0) %>%
    ts_simplify() %>%
    ts_mutate(mutation_rate = 1e-4)
  
  # extract full genealogies trees
  tsu <- ts_load(model, simplify = FALSE) 

  # collect trees
  trees <- c(trees,ts)
  trees_us <- c(trees_us,tsu)

  print(paste("Simulation number:",i))
  i <- i+1
}

# getting out the tree objects
trees_phylo <- lapply(trees, ts_phylo, i=1, quiet=TRUE) # convert
class(trees_phylo) <-  "multiPhylo" # convert list

tree_data <- data.frame()

# merge all the spatial tree data into a dataframe to plot
for (row in c(1:dim(pars)[1])){

  tree <- trees_phylo[[row]]

  tree_data_i <- tree %>% ts_data() %>% rowwise() %>% mutate(N=pars[row,"N"],
                                               fun=pars[row,"disp_fun"],
                                               rep=as.factor(pars[row,"rep"]),
                                               mat_dist=pars[row,"mat_dist"],
                                               comp_dist=pars[row,"comp_dist"],
                                               disp_dist=pars[row,"disp_dist"],
                                               sim=as.factor(row),
                                               x=unlist(location)[1],
                                               y=unlist(location)[2]) %>% ungroup()

  tree_data <- rbind(tree_data,tree_data_i)
  #print(paste("Converting tree no",row))
}
```


